# RUNTIME ==========
seed: 42


# MODEL ==========
model:
  name:
  params:


# PIPELINE PACKAGE ==========
split:
  ratio:
    trn: 0.6
    val: 0.2
    tst: 0.2
  shuffle: True

dataloader:
  batch_size: 1024
  shuffle: True


# TRAINER PACKAGE ==========
trainer:
  num_epochs: 100

loss:
  name: bce
  params:

optimizer:
  name: adamw
  params:
    lr: 0.0001
    weight_decay: 0.0001

monitor:
  delta: 0.0001
  patience: 5
  warmup: 0
